name: mds_project
channels:
    - pytorch
    - pyg
    - conda-forge
    - nodefaults
dependencies:
    - conda-forge::python
    - conda-forge::numpy
    - conda-forge::scipy
    - conda-forge::pandas
    - conda-forge::scikit-learn
    - conda-forge::matplotlib
    - conda-forge::pip
    - pytorch::pytorch==1.11.0
    - pip:
        - pycorruptor==0.0.4
        - tsdb==0.0.7
